In [450]:
import numpy as np
import pandas as pd

from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report
from sklearn.metrics import accuracy_score

In [451]:
df_fruit = pd.read_excel('fruit_data.xlsx')
df_fruit.head

<bound method NDFrame.head of       diameter  weight  red  green  blue        name
0         2.96   86.76  172     85     2      orange
1         3.91   88.05  166     78     3      orange
2         4.42   95.17  156     81     2      orange
3         4.47   95.60  163     81     4      orange
4         4.48   95.76  161     72     9      orange
...        ...     ...  ...    ...   ...         ...
9995     15.35  253.89  149     77    20  grapefruit
9996     15.41  254.67  148     68     7  grapefruit
9997     15.59  256.50  168     82    20  grapefruit
9998     15.92  260.14  142     72    11  grapefruit
9999     16.45  261.51  152     74     2  grapefruit

[10000 rows x 6 columns]>

In [452]:
df_fruit.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 6 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   diameter  10000 non-null  float64
 1   weight    10000 non-null  float64
 2   red       10000 non-null  int64  
 3   green     10000 non-null  int64  
 4   blue      10000 non-null  int64  
 5   name      10000 non-null  object 
dtypes: float64(2), int64(3), object(1)
memory usage: 468.9+ KB


In [453]:
df_fruit.empty

False

In [454]:
en = LabelEncoder()

df_fruit['name'] = en.fit_transform(df_fruit['name'])
df_fruit.head

<bound method NDFrame.head of       diameter  weight  red  green  blue  name
0         2.96   86.76  172     85     2     1
1         3.91   88.05  166     78     3     1
2         4.42   95.17  156     81     2     1
3         4.47   95.60  163     81     4     1
4         4.48   95.76  161     72     9     1
...        ...     ...  ...    ...   ...   ...
9995     15.35  253.89  149     77    20     0
9996     15.41  254.67  148     68     7     0
9997     15.59  256.50  168     82    20     0
9998     15.92  260.14  142     72    11     0
9999     16.45  261.51  152     74     2     0

[10000 rows x 6 columns]>

In [455]:
x = df_fruit.iloc[:, :-1].values
y = df_fruit.iloc[:, -1].values

In [456]:
x

array([[  2.96,  86.76, 172.  ,  85.  ,   2.  ],
       [  3.91,  88.05, 166.  ,  78.  ,   3.  ],
       [  4.42,  95.17, 156.  ,  81.  ,   2.  ],
       ...,
       [ 15.59, 256.5 , 168.  ,  82.  ,  20.  ],
       [ 15.92, 260.14, 142.  ,  72.  ,  11.  ],
       [ 16.45, 261.51, 152.  ,  74.  ,   2.  ]])

In [457]:
y

array([1, 1, 1, ..., 0, 0, 0])

In [458]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=123)

print("x_train = ", len(x_train))
print("x_test = ", len(x_test))
print("y_train = ", len(y_train))
print("y_test = ", len(y_test))

x_train =  8000
x_test =  2000
y_train =  8000
y_test =  2000


In [459]:
sc =StandardScaler()

x_train = sc.fit_transform(x_train)
x_test = sc.transform(x_test)

In [460]:
x_train

array([[ 1.40581808,  1.4183702 , -0.27199554,  1.19324519, -1.03227097],
       [ 0.69304398,  0.69950687,  0.39571226,  0.08064231,  0.39822925],
       [-1.35297665, -1.34325454,  0.77725958, -0.00494252,  0.06811382],
       ...,
       [-0.31201879, -0.3847701 ,  0.58648592, -0.34728187,  0.28819078],
       [-1.15811755, -1.16721335,  0.68187275,  1.10766035, -0.48207858],
       [-0.41457621, -0.40015234,  0.77725958,  1.87792388, -1.03227097]])

In [461]:
x_test

array([[-0.72224849, -0.7310414 , -1.03509018, -0.00494252, -1.03227097],
       [-1.63500957, -1.63175699,  0.68187275,  0.93649068, -0.81219401],
       [ 1.58529358,  1.5957787 ,  0.87264641, -0.77520605,  0.50826773],
       ...,
       [-0.64533042, -0.64729366,  1.1588069 ,  2.47701774, -0.70215553],
       [ 0.87764734,  0.89434857,  1.06342007, -2.0589786 , -1.03227097],
       [-1.52219641, -1.48682211,  1.82651471,  0.59415133, -0.04192466]])

In [462]:
y_train

array([0, 0, 1, ..., 0, 1, 1])

In [463]:
y_test

array([1, 1, 0, ..., 1, 0, 1])

In [464]:
classifier = GaussianNB()
classifier.fit(x_train, y_train)

GaussianNB()

In [465]:
y_pred = classifier.predict(x_test)
y_pred

array([1, 1, 0, ..., 1, 0, 1])

In [466]:
classifier.predict_proba(x_test)

array([[2.91609281e-03, 9.97083907e-01],
       [3.73045370e-07, 9.99999627e-01],
       [9.99997219e-01, 2.78115682e-06],
       ...,
       [5.50292701e-05, 9.99944971e-01],
       [9.99456947e-01, 5.43053358e-04],
       [1.58064364e-06, 9.99998419e-01]])

In [467]:
cm = confusion_matrix(y_test, y_pred)
print(cm)

[[915  91]
 [ 66 928]]


In [468]:
akurasi = classification_report(y_test, y_pred)
print(akurasi)

              precision    recall  f1-score   support

           0       0.93      0.91      0.92      1006
           1       0.91      0.93      0.92       994

    accuracy                           0.92      2000
   macro avg       0.92      0.92      0.92      2000
weighted avg       0.92      0.92      0.92      2000



In [469]:
akurasi = accuracy_score(y_test, y_pred)
print("tingkat akurasi : %d persen "%(akurasi*100))

tingkat akurasi : 92 persen 


In [470]:
ydata = pd.DataFrame()
ydata['y_test'] = pd.DataFrame(y_test)
ydata['y_pred'] = pd.DataFrame(y_pred)
ydata

y_test  y_pred
0          1       1
1          1       1
2          0       0
3          1       1
4          1       1
...      ...     ...
1995       0       0
1996       0       0
1997       1       1
1998       0       0
1999       1       1

[2000 rows x 2 columns]

In [471]:
ydata.to_excel('data fruit actualpred.xlsx', index=False)

# Save Model

In [472]:
import pickle

filename = 'NaiveBayes_Fruit.sav'
pickle.dump(classifier, open(filename,'wb'))
